version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
  user-service:
    image: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresSQLConnection=Host=postgres;Port=5432;Database=appdb;Username=appuser;Password=secret
    ports:
      - "5001:7000"
      - "6001:7001"
    networks:
      - app-network
    depends_on:
      - postgres
  message-service:
    image: message-service
    ports:
      - "5000:7000"
      - "6000:7001"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://root:secret@mongodb:27017
      - ConnectionStrings__MongoDbName=MessageMongoDb
    depends_on:
      - mongodb
  realtime-service-ts:
    image: realtime-service-ts
    ports:
      - "8081:8080"
    env_file:
      - ./realtime-service-ts/production.env
    networks:
      - app-network
    depends_on:
      - user-service
      - message-service
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_URL: ws://realtime-service-ts:8080
      - NEXT_PUBLIC_MESSAGE_SERVICE_URL: http://message-service:7000
      - NEXT_PUBLIC_USER_SERVICE_URL: http://user-service:7000
    networks:
      - app-network
    depends_on:
      - user-service
      - message-service
      - realtime-service-ts
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - postgres
volumes:
  pgdata:
    driver: local
  mongodata:
    driver: local
  pgadmin_data:
    driver: local
networks:
  app-network:
    driver: bridge